# Generated by Django 3.1.7 on 2021-04-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0002_auto_20210405_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='epub',
            field=models.FileField(blank=True, null=True, upload_to='documents/epub/'),
        ),
        migrations.AddField(
            model_name='book',
            name='mobi',
            field=models.FileField(blank=True, null=True, upload_to='documents/mobi/'),
        ),
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(null=True, upload_to='documents/pdf/'),
        ),
    ]
